[package]
name = "edge-dhcp"
version = "0.1.0"
edition = "2021"

[features]
default = ["nightly"]
nightly = ["embassy-futures", "embedded-nal-async"]

[dependencies]
no-std-net = { workspace = true }
heapless = { workspace = true }
log = { workspace = true }
rand_core = "0.6"
embassy-futures = { workspace = true, optional = true }
embassy-time = { workspace = true, default-features = false } # TODO: Make optional
embedded-nal-async = { workspace = true, optional = true }
num_enum = { version = "0.7", default-features = false }
edge-raw = { workspace = true, default-features = false }
