[package]
name = "edge-captive"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[features]
std = [] # TODO
default = ["io"]
io = ["embedded-nal-async"]

[dependencies]
log = { workspace = true }
domain = { workspace = true }
octseq = { workspace = true }
embedded-nal-async = { workspace = true, optional = true }