[package]
name = "edge-mqtt"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
rumqttc = "0.19"
log = { workspace = true }
embedded-svc = { workspace = true, optional = true, default-features = false, features = ["std"] }
