[package]
name = "edge-raw"
version = "0.2.0"
edition = "2021"
rust-version = "1.75"
description = "Async + `no_std` + no-alloc implementation of IP and UDP packet creation and parsing"
repository = "https://github.com/ivmarkov/edge-net"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
    "asynchronous",
    "networking",
    "ip"
]

[features]
default = ["io"]
std = ["io"]
io = ["embedded-io-async", "embedded-nal-async", "embedded-nal-async-xtra"]

[dependencies]
log = { workspace = true }
no-std-net = { workspace = true }
embedded-io-async = { workspace = true, default-features = false, optional = true }
embedded-nal-async = { workspace = true, default-features = false, optional = true }
embedded-nal-async-xtra = { workspace = true, default-features = false, optional = true }
