name: PublishCrate

on:
  workflow_dispatch:
    inputs:
      crate:
        required: true
        type: choice
        description: Crate to publish
        options: 
        - embedded-nal-async-xtra
        - edge-std-nal-async
        - edge-captive
        - edge-dhcp
        - edge-http
        - edge-mdns
        - edge-mqtt
        - edge-raw
        - edge-ws

env:
  rust_toolchain: stable

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
      - name: Setup | Std
        run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      - name: Setup | Set default toolchain
        run: rustup default ${{ env.rust_toolchain }}
      - name: Login
        run: cargo login ${{ secrets.crates_io_token }}
      - name: Build | Publish
        run: cd "${{ github.event.inputs.crate }}"; cargo publish
